### PR TITLE
feat: Supporting GitHubs new draft status for PRs

### LINKED ISSUE #164: Add `PR: draft` status label.
Add draft status label.

### PR DESCRIPTION
**Pull request by tannakartikey**
Github announced new draft status for PRs.
https://developer.github.com/changes/2019-02-14-draft-pull-requests/

It can be seen in action over here:
https://github.com/tannakartikey/app/pull/6

fix #164

### CODE REVIEW

**Comment by sotayamashita** [comment]
@tannakartikey I appreciate your PR. Let me review this amazing PR in 5 days. Thanks again. :smile:

**Comment by sotayamashita** [comment]
Finally, let me check how it works in my computer before merging.

**Comment by tannakartikey** [comment]
@sotayamashita so, did it work as expected?

**Comment by sotayamashita** [comment]
@tannakartikey I am sorry to be late. I'll do it now.

**Comment by tannakartikey** [comment]
@sotayamashita thanks for the review. I have implemented the changes.

**Comment by sotayamashita** [comment]
@tannakartikey Thank you for quick fix. I'll review it again.

**Comment by sotayamashita** [comment]
@tannakartikey Thanks I merged.

**Pull request merged**
